from __future__ import annotations
import shutil
from pathlib import Path
from .io import write_text, write_json, clean_dir
from .formatters import (
    android_color_name, pascal_case, camel_case, kotlin_float,
    kotlin_symbol, kotlin_color_literal, kotlin_accent_symbol, kotlin_gradient_symbol,
    kotlin_sp, kotlin_font_ref, swift_color_name, argb_literal, swift_case_name,
    resource_alias_name, format_number
)
from .validation import validate

def generate_metadata(tokens: dict, out_dir: Path) -> None:
    write_json(out_dir / "metadata" / "yalla-design.json", tokens)

# region Android Emitters

def color_rows(colors: dict, scheme: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for group_name, group in colors["schemes"][scheme].items():
        for token_name, color in group.items():
            rows.append((android_color_name((group_name, token_name)), color))
    for token_name, color in colors["accent"].items():
        rows.append((android_color_name(("accent", token_name)), color))
    for gradient_name, stops in colors["gradients"].items():
        for index, stop in enumerate(stops):
            rows.append((android_color_name(("gradient", gradient_name, str(index))), stop["color"]))
    return rows

def generate_android_colors(tokens: dict, out_dir: Path) -> None:
    for folder, scheme in (("values", "light"), ("values-night", "dark")):
        rows = color_rows(tokens["colors"], scheme)
        lines = [
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
            "<!-- Generated by yalla-design. Do not edit manually. -->",
            "<resources>",
        ]
        lines.extend(f"    <color name=\"{name}\">{color}</color>" for name, color in rows)
        lines.append("</resources>")
        write_text(out_dir / "android" / "design" / "src" / "main" / "res" / folder / "colors.xml", "\n".join(lines) + "\n")

def generate_android_themed_image_drawables(tokens: dict, out_dir: Path) -> None:
    for variant, folder in (("light", "drawable"), ("dark", "drawable-night")):
        for image in tokens["themedImages"]["images"]:
            lines = [
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
                "<!-- Generated by yalla-design. Do not edit manually. -->",
                "<bitmap xmlns:android=\"http://schemas.android.com/apk/res/android\"",
                f"    android:src=\"@drawable/{image[variant]}\" />",
            ]
            filename = resource_alias_name(image['name']) + ".xml"
            write_text(out_dir / "android" / "design" / "src" / "main" / "res" / folder / filename, "\n".join(lines) + "\n")

def generate_android_color_helpers(tokens: dict, out_dir: Path) -> None:
    colors = tokens["colors"]
    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import uz.yalla.sdk.android.design.R",
        "",
        "object YallaColors {",
    ]
    for group_name, group in colors["schemes"]["light"].items():
        lines.append(f"    object {pascal_case(group_name)} {{")
        for token_name in group:
            lines.append(f"        val {camel_case(token_name)}: Int get() = R.color.{android_color_name((group_name, token_name))}")
        lines.append("    }")
        lines.append("")
    lines.append("    object Accent {")
    for token_name in tokens["colors"]["accent"]:
        lines.append(f"        val {camel_case(token_name)}: Int get() = R.color.{android_color_name(('accent', token_name))}")
    lines.append("    }")
    lines.append("")
    lines.append("    object Gradient {")
    for gradient_name, stops in colors["gradients"].items():
        resource_names = ", ".join(f"R.color.{android_color_name(('gradient', gradient_name, str(index)))}" for index, _ in enumerate(stops))
        lines.append(f"        val {camel_case(gradient_name)}: IntArray get() = intArrayOf({resource_names})")
    lines.append("    }")
    lines.append("}")
    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "YallaColors.kt", "\n".join(lines) + "\n")

def generate_android_fonts_helpers(tokens: dict, out_dir: Path) -> None:
    styles = tokens["fonts"]["styles"]
    resources = tokens["fonts"]["fontResources"]["android"]

    def style_expr(key: str) -> str:
        style = styles[key]
        return (
            f"YallaTextStyle(fontRes = R.font.{resources[style['font']]}, "
            f"sizeSp = {kotlin_float(style['sizeSp'])}, "
            f"lineHeightSp = {kotlin_float(style['lineHeightSp'])})"
        )

    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import uz.yalla.sdk.android.design.R",
        "",
        "data class YallaTextStyle(",
        "    val fontRes: Int,",
        "    val sizeSp: Float,",
        "    val lineHeightSp: Float",
        ")",
        "",
        "object YallaFonts {",
        "    object Title {",
        f"        val xLarge: YallaTextStyle = {style_expr('title.xLarge')}",
        f"        val large: YallaTextStyle = {style_expr('title.large')}",
        f"        val base: YallaTextStyle = {style_expr('title.base')}",
        "    }",
        "",
        "    object Body {",
        f"        val caption: YallaTextStyle = {style_expr('body.caption')}",
        "",
        "        object Large {",
        f"            val regular: YallaTextStyle = {style_expr('body.large.regular')}",
        f"            val medium: YallaTextStyle = {style_expr('body.large.medium')}",
        f"            val bold: YallaTextStyle = {style_expr('body.large.bold')}",
        "        }",
        "",
        "        object Base {",
        f"            val regular: YallaTextStyle = {style_expr('body.base.regular')}",
        f"            val medium: YallaTextStyle = {style_expr('body.base.medium')}",
        f"            val bold: YallaTextStyle = {style_expr('body.base.bold')}",
        "        }",
        "",
        "        object Small {",
        f"            val regular: YallaTextStyle = {style_expr('body.small.regular')}",
        f"            val medium: YallaTextStyle = {style_expr('body.small.medium')}",
        f"            val bold: YallaTextStyle = {style_expr('body.small.bold')}",
        "        }",
        "    }",
        "",
        "    object Custom {",
        f"        val carNumber: YallaTextStyle = {style_expr('custom.carNumber')}",
        "    }",
        "}",
    ]
    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "YallaFonts.kt", "\n".join(lines) + "\n")

def generate_android_themed_image_helpers(tokens: dict, out_dir: Path) -> None:
    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import uz.yalla.sdk.android.design.R",
        "",
        "enum class YallaThemedImage(val resId: Int) {",
    ]
    images = tokens["themedImages"]["images"]
    for index, image in enumerate(images):
        suffix = "," if index < len(images) - 1 else ";"
        lines.append(f"    {image['name']}(R.drawable.{resource_alias_name(image['name'])}){suffix}")
    lines.append("}")
    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "YallaThemedImage.kt", "\n".join(lines) + "\n")

def generate_android_color_scheme(tokens: dict, out_dir: Path) -> None:
    colors = tokens["colors"]
    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.runtime.Immutable",
        "import androidx.compose.runtime.staticCompositionLocalOf",
        "import androidx.compose.ui.graphics.Brush",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.res.colorResource",
        "import uz.yalla.sdk.android.design.R",
        "",
        "@Immutable",
        "public data class ColorScheme(",
    ]
    
    # Define primary properties
    for group in ["text", "background", "border", "button", "icon", "accent"]:
        lines.append(f"    public val {group}: {pascal_case(group)},")
    lines.append("    public val gradient: Gradient")
    lines.append(")")
    lines.append("")

    # Define sub-classes
    for group_name, group in colors["schemes"]["light"].items():
        lines.append("    @Immutable")
        lines.append(f"    public data class {pascal_case(group_name)}(")
        for token_name in group:
            lines.append(f"        public val {camel_case(token_name)}: Color,")
        lines[-1] = lines[-1].rstrip(",")
        lines.append("    )")
        lines.append("")

    lines.append("    @Immutable")
    lines.append("    public data class Accent(")
    for token_name in colors["accent"]:
        lines.append(f"        public val {camel_case(token_name)}: Color,")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("    )")
    lines.append("")

    lines.append("    @Immutable")
    lines.append("    public data class Gradient(")
    for gradient_name in colors["gradients"]:
        lines.append(f"        public val {camel_case(gradient_name)}: Brush,")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("    )")
    lines.append("")

    # rememberColorScheme
    lines.append("@Composable")
    lines.append("public fun rememberColorScheme(): ColorScheme = ColorScheme(")
    for group_name, group in colors["schemes"]["light"].items():
        lines.append(f"    {group_name} = ColorScheme.{pascal_case(group_name)}(")
        for token_name in group:
            lines.append(f"        {camel_case(token_name)} = colorResource(R.color.{android_color_name((group_name, token_name))}),")
        lines[-1] = lines[-1].rstrip(",")
        lines.append("    ),")
    
    lines.append("    accent = ColorScheme.Accent(")
    for token_name in colors["accent"]:
        lines.append(f"        {camel_case(token_name)} = colorResource(R.color.{android_color_name(('accent', token_name))}),")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("    ),")

    lines.append("    gradient = ColorScheme.Gradient(")
    for gradient_name, stops in colors["gradients"].items():
        colors_list = ", ".join(f"colorResource(R.color.{android_color_name(('gradient', gradient_name, str(i)))})" for i in range(len(stops)))
        lines.append(f"        {camel_case(gradient_name)} = Brush.linearGradient(listOf({colors_list})),")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("    )")
    lines.append(")")
    lines.append("")
    lines.append("public val LocalColorScheme = staticCompositionLocalOf {")
    lines.append("    error(\"No ColorScheme provided\")")
    lines.append("}")

    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "ColorScheme.kt", "\n".join(lines) + "\n")

def generate_android_font_scheme(tokens: dict, out_dir: Path) -> None:
    styles = tokens["fonts"]["styles"]
    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.runtime.Immutable",
        "import androidx.compose.runtime.staticCompositionLocalOf",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.Font",
        "import androidx.compose.ui.text.font.FontFamily",
        "import androidx.compose.ui.unit.sp",
        "import uz.yalla.sdk.android.design.R",
        "",
        "@Immutable",
        "public data class FontScheme(",
        "    public val title: Title,",
        "    public val body: Body,",
        "    public val custom: Custom",
        ") {",
        "    @Immutable",
        "    public data class Title(",
        "        public val xLarge: TextStyle,",
        "        public val large: TextStyle,",
        "        public val base: TextStyle",
        "    )",
        "",
        "    @Immutable",
        "    public data class Body(",
        "        public val caption: TextStyle,",
        "        public val large: Weighty,",
        "        public val base: Weighty,",
        "        public val small: Weighty",
        "    ) {",
        "        @Immutable",
        "        public data class Weighty(",
        "            public val regular: TextStyle,",
        "            public val medium: TextStyle,",
        "            public val bold: TextStyle",
        "        )",
        "    }",
        "",
        "    @Immutable",
        "    public data class Custom(",
        "        public val carNumber: TextStyle",
        "    )",
        "}",
        "",
        "public val LocalFontScheme = staticCompositionLocalOf<FontScheme> {",
        "    error(\"No FontScheme provided\")",
        "}",
        "",
        "@Composable",
        "public fun rememberFontScheme(): FontScheme {",
    ]

    # Helper to load font family
    roles = ["normal", "medium", "bold", "carNumber"]
    for role in roles:
        res = tokens["fonts"]["fontResources"]["android"][role]
        lines.append(f"    val {role}Font = FontFamily(Font(R.font.{res}))")
    lines.append("")

    def style_expr(key: str) -> str:
        style = styles[key]
        return (
            f"TextStyle("
            f"fontFamily = {style['font']}Font, "
            f"fontSize = {kotlin_sp(style['sizeSp'])}, "
            f"lineHeight = {kotlin_sp(style['lineHeightSp'])})"
        )

    lines.extend([
        "    return FontScheme(",
        "        title = FontScheme.Title(",
        f"            xLarge = {style_expr('title.xLarge')},",
        f"            large = {style_expr('title.large')},",
        f"            base = {style_expr('title.base')}",
        "        ),",
        "        body = FontScheme.Body(",
        f"            caption = {style_expr('body.caption')},",
        "            large = FontScheme.Body.Weighty(",
        f"                regular = {style_expr('body.large.regular')},",
        f"                medium = {style_expr('body.large.medium')},",
        f"                bold = {style_expr('body.large.bold')}",
        "            ),",
        "            base = FontScheme.Body.Weighty(",
        f"                regular = {style_expr('body.base.regular')},",
        f"                medium = {style_expr('body.base.medium')},",
        f"                bold = {style_expr('body.base.bold')}",
        "            ),",
        "            small = FontScheme.Body.Weighty(",
        f"                regular = {style_expr('body.small.regular')},",
        f"                medium = {style_expr('body.small.medium')},",
        f"                bold = {style_expr('body.small.bold')}",
        "            )",
        "        ),",
        "        custom = FontScheme.Custom(",
        f"            carNumber = {style_expr('custom.carNumber')}",
        "        )",
        "    )",
        "}"
    ])

    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "FontScheme.kt", "\n".join(lines) + "\n")

def generate_android_theme(tokens: dict, out_dir: Path) -> None:
    lines = [
        "package uz.yalla.sdk.android.design",
        "",
        "import androidx.compose.foundation.isSystemInDarkTheme",
        "import androidx.compose.material3.MaterialTheme",
        "import androidx.compose.material3.darkColorScheme as materialDarkColorScheme",
        "import androidx.compose.material3.lightColorScheme as materialLightColorScheme",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.runtime.CompositionLocalProvider",
        "import androidx.compose.runtime.ReadOnlyComposable",
        "",
        "@Composable",
        "public fun YallaTheme(",
        "    isDark: Boolean = isSystemInDarkTheme(),",
        "    colorScheme: ColorScheme = rememberColorScheme(),",
        "    fontScheme: FontScheme = rememberFontScheme(),",
        "    content: @Composable () -> Unit",
        ") {",
        "    val materialColorScheme = if (isDark) {",
        "        materialDarkColorScheme(",
        "            primary = colorScheme.button.active,",
        "            onPrimary = colorScheme.text.white,",
        "            secondary = colorScheme.button.secondary,",
        "            tertiary = colorScheme.button.tertiary,",
        "            background = colorScheme.background.base,",
        "            surface = colorScheme.background.secondary,",
        "            error = colorScheme.text.red,",
        "            onBackground = colorScheme.text.base,",
        "            onSurface = colorScheme.text.base",
        "        )",
        "    } else {",
        "        materialLightColorScheme(",
        "            primary = colorScheme.button.active,",
        "            onPrimary = colorScheme.text.white,",
        "            secondary = colorScheme.button.secondary,",
        "            tertiary = colorScheme.button.tertiary,",
        "            background = colorScheme.background.base,",
        "            surface = colorScheme.background.secondary,",
        "            error = colorScheme.text.red,",
        "            onBackground = colorScheme.text.base,",
        "            onSurface = colorScheme.text.base",
        "        )",
        "    }",
        "",
        "    CompositionLocalProvider(",
        "        LocalColorScheme provides colorScheme,",
        "        LocalFontScheme provides fontScheme",
        "    ) {",
        "        MaterialTheme(",
        "            colorScheme = materialColorScheme,",
        "            content = content",
        "        )",
        "    }",
        "}",
        "",
        "public object System {",
        "    public val color: ColorScheme",
        "        @Composable",
        "        @ReadOnlyComposable",
        "        get() = LocalColorScheme.current",
        "",
        "    public val font: FontScheme",
        "        @Composable",
        "        @ReadOnlyComposable",
        "        get() = LocalFontScheme.current",
        "}",
    ]
    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design" / "Theme.kt", "\n".join(lines) + "\n")

def generate_android_design(tokens: dict, out_dir: Path) -> None:
    generate_android_colors(tokens, out_dir)
    generate_android_themed_image_drawables(tokens, out_dir)
    generate_android_color_helpers(tokens, out_dir)
    generate_android_fonts_helpers(tokens, out_dir)
    generate_android_themed_image_helpers(tokens, out_dir)
    generate_android_color_scheme(tokens, out_dir)
    generate_android_font_scheme(tokens, out_dir)
    generate_android_theme(tokens, out_dir)

# endregion

# region CMP Emitters

def generate_cmp_colors(tokens: dict, out_dir: Path) -> None:
    colors = tokens["colors"]
    lines = [
        "package uz.yalla.design.color",
        "",
        "import androidx.compose.ui.geometry.Offset",
        "import androidx.compose.ui.graphics.Brush",
        "import androidx.compose.ui.graphics.Color",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
    ]
    for scheme in ("light", "dark"):
        lines.append(f"// region {pascal_case(scheme)} Theme Colors")
        lines.append("")
        for group_name, group in colors["schemes"][scheme].items():
            for token_name, color in group.items():
                lines.append(f"internal val {kotlin_symbol((scheme, group_name, token_name))} = {kotlin_color_literal(color)}")
        lines.append("")
        lines.append("// endregion")
        lines.append("")
    lines.append("// region Accent Colors")
    lines.append("")
    for token_name, color in colors["accent"].items():
        lines.append(f"internal val {kotlin_accent_symbol(token_name)} = {kotlin_color_literal(color)}")
    lines.append("")
    lines.append("// endregion")
    lines.append("")
    lines.append("// region Gradients")
    lines.append("")
    for gradient_name, stops in colors["gradients"].items():
        symbol = kotlin_gradient_symbol(gradient_name)
        stop_values = ", ".join(kotlin_color_literal(stop["color"]) for stop in stops)
        if gradient_name == "splash":
            lines.extend(
                [
                    f"internal val {symbol} =",
                    "    Brush.linearGradient(",
                    f"        colors = listOf({stop_values}),",
                    "        start = Offset(0f, 0f),",
                    "        end = Offset(1000f, 1000f)",
                    "    )",
                ]
            )
        else:
            lines.append(f"internal val {symbol} = Brush.linearGradient(listOf({stop_values}))")
        lines.append("")
    lines.append("// endregion")
    write_text(
        out_dir / "cmp" / "design" / "src" / "commonMain" / "kotlin" / "uz" / "yalla" / "design" / "color" / "Color.kt",
        "\n".join(lines).rstrip() + "\n",
    )

def kotlin_text_style(style: dict, indent: int) -> list[str]:
    space = " " * indent
    inner = " " * (indent + 4)
    return [
        f"{space}TextStyle(",
        f"{inner}fontSize = {kotlin_sp(style['sizeSp'])},",
        f"{inner}lineHeight = {kotlin_sp(style['lineHeightSp'])},",
        f"{inner}fontFamily = FontFamily(Font({kotlin_font_ref(style['font'])}))",
        f"{space})",
    ]

def with_comma(lines: list[str]) -> list[str]:
    copied = list(lines)
    copied[-1] += ","
    return copied

def generate_cmp_font_common(tokens: dict, out_dir: Path) -> None:
    styles = tokens["fonts"]["styles"]
    lines = [
        "package uz.yalla.design.font",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.FontFamily",
        "import androidx.compose.ui.unit.sp",
        "import org.jetbrains.compose.resources.Font",
        "import org.jetbrains.compose.resources.FontResource",
        "import uz.yalla.resources.Res",
        "import uz.yalla.resources.nummernschild",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "expect val boldFont: FontResource",
        "expect val mediumFont: FontResource",
        "expect val normalFont: FontResource",
        "",
        "@Composable",
        "fun rememberFontScheme(): FontScheme =",
        "    FontScheme(",
        "        title =",
        "            FontScheme.Title(",
        "                xLarge =",
        *with_comma(kotlin_text_style(styles["title.xLarge"], 20)),
        "                large =",
        *with_comma(kotlin_text_style(styles["title.large"], 20)),
        "                base =",
        *kotlin_text_style(styles["title.base"], 20),
        "            ),",
        "        body =",
        "            FontScheme.Body(",
        "                caption =",
        *with_comma(kotlin_text_style(styles["body.caption"], 20)),
        "                large =",
        "                    FontScheme.Body.Weighty(",
        "                        regular =",
        *with_comma(kotlin_text_style(styles["body.large.regular"], 28)),
        "                        medium =",
        *with_comma(kotlin_text_style(styles["body.large.medium"], 28)),
        "                        bold =",
        *kotlin_text_style(styles["body.large.bold"], 28),
        "                    ),",
        "                base =",
        "                    FontScheme.Body.Weighty(",
        "                        regular =",
        *with_comma(kotlin_text_style(styles["body.base.regular"], 28)),
        "                        medium =",
        *with_comma(kotlin_text_style(styles["body.base.medium"], 28)),
        "                        bold =",
        *kotlin_text_style(styles["body.base.bold"], 28),
        "                    ),",
        "                small =",
        "                    FontScheme.Body.Weighty(",
        "                        regular =",
        *with_comma(kotlin_text_style(styles["body.small.regular"], 28)),
        "                        medium =",
        *with_comma(kotlin_text_style(styles["body.small.medium"], 28)),
        "                        bold =",
        *kotlin_text_style(styles["body.small.bold"], 28),
        "                    )",
        "            ),",
        "        custom =",
        "            FontScheme.Custom(",
        "                carNumber =",
        *kotlin_text_style(styles["custom.carNumber"], 20),
        "            )",
        "    )",
    ]
    write_text(
        out_dir / "cmp" / "design" / "src" / "commonMain" / "kotlin" / "uz" / "yalla" / "design" / "font" / "Font.kt",
        "\n".join(lines) + "\n",
    )

def generate_cmp_font_platform(tokens: dict, out_dir: Path, platform: str, source_set: str) -> None:
    resources = tokens["fonts"]["fontResources"][platform]
    lines = [
        "package uz.yalla.design.font",
        "",
        "import org.jetbrains.compose.resources.FontResource",
        "import uz.yalla.resources.Res",
        f"import uz.yalla.resources.{resources['bold']}",
        f"import uz.yalla.resources.{resources['medium']}",
        f"import uz.yalla.resources.{resources['normal']}",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        f"actual val boldFont: FontResource = Res.font.{resources['bold']}",
        f"actual val mediumFont: FontResource = Res.font.{resources['medium']}",
        f"actual val normalFont: FontResource = Res.font.{resources['normal']}",
    ]
    write_text(
        out_dir / "cmp" / "design" / "src" / source_set / "kotlin" / "uz" / "yalla" / "design" / "font" / f"Font.{source_set.removesuffix('Main')}.kt",
        "\n".join(lines) + "\n",
    )

def generate_cmp_themed_images(tokens: dict, out_dir: Path) -> None:
    images = tokens["themedImages"]["images"]
    resource_names = sorted({image["light"] for image in images} | {image["dark"] for image in images})
    lines = [
        "package uz.yalla.design.image",
        "",
        "import org.jetbrains.compose.resources.DrawableResource",
        "import uz.yalla.resources.Res",
        *[f"import uz.yalla.resources.{resource_name}" for resource_name in resource_names],
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "enum class ThemedImage(",
        "    val light: DrawableResource,",
        "    val dark: DrawableResource",
        ") {",
    ]
    for index, image in enumerate(images):
        suffix = "," if index < len(images) - 1 else ""
        lines.append(f"    {image['name']}(Res.drawable.{image['light']}, Res.drawable.{image['dark']}){suffix}")
    lines.append("}")
    write_text(
        out_dir / "cmp" / "design" / "src" / "commonMain" / "kotlin" / "uz" / "yalla" / "design" / "image" / "ThemedImage.kt",
        "\n".join(lines) + "\n",
    )

def generate_cmp_design(tokens: dict, out_dir: Path) -> None:
    generate_cmp_colors(tokens, out_dir)
    generate_cmp_font_common(tokens, out_dir)
    generate_cmp_font_platform(tokens, out_dir, "cmpAndroid", "androidMain")
    generate_cmp_font_platform(tokens, out_dir, "cmpIos", "iosMain")
    generate_cmp_themed_images(tokens, out_dir)

# endregion

# region iOS Emitters

def generate_ios_colors(tokens: dict, out_dir: Path) -> None:
    colors = tokens["colors"]
    lines = [
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "public typealias YallaNativeColor = UIColor",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "public typealias YallaNativeColor = NSColor",
        "#endif",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public enum YallaUIColor {",
    ]
    for group_name, group in colors["schemes"]["light"].items():
        for token_name, light_color in group.items():
            dark_color = colors["schemes"]["dark"][group_name][token_name]
            lines.append(
                f"    public static let {swift_color_name((group_name, token_name))}: YallaNativeColor = dynamic(light: {argb_literal(light_color)}, dark: {argb_literal(dark_color)})"
            )
    for token_name, color in colors["accent"].items():
        lines.append(f"    public static let {swift_color_name(('accent', token_name))}: YallaNativeColor = fixed({argb_literal(color)})")
    for gradient_name, stops in colors["gradients"].items():
        values = ", ".join(f"fixed({argb_literal(stop['color'])})" for stop in stops)
        lines.append(f"    public static let {swift_color_name(('gradient', gradient_name))}: [YallaNativeColor] = [{values}]")
    lines.extend(
        [
            "",
            "    private static func dynamic(light: UInt32, dark: UInt32) -> YallaNativeColor {",
            "        #if canImport(UIKit)",
            "        return UIColor { traitCollection in",
            "            return traitCollection.userInterfaceStyle == .dark ? color(dark) : color(light)",
            "        }",
            "        #elseif canImport(AppKit)",
            "        return NSColor(name: nil) { appearance in",
            "            let bestMatch = appearance.bestMatch(from: [.aqua, .darkAqua])",
            "            return bestMatch == .darkAqua ? color(dark) : color(light)",
            "        }",
            "        #endif",
            "    }",
            "",
            "    private static func fixed(_ argb: UInt32) -> YallaNativeColor {",
            "        return color(argb)",
            "    }",
            "",
            "    private static func color(_ argb: UInt32) -> YallaNativeColor {",
            "        #if canImport(UIKit)",
            "        return UIColor(",
            "            red: CGFloat((argb >> 16) & 0xFF) / 255.0,",
            "            green: CGFloat((argb >> 8) & 0xFF) / 255.0,",
            "            blue: CGFloat(argb & 0xFF) / 255.0,",
            "            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0",
            "        )",
            "        #elseif canImport(AppKit)",
            "        return NSColor(",
            "            red: CGFloat((argb >> 16) & 0xFF) / 255.0,",
            "            green: CGFloat((argb >> 8) & 0xFF) / 255.0,",
            "            blue: CGFloat(argb & 0xFF) / 255.0,",
            "            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0",
            "        )",
            "        #endif",
            "    }",
            "}",
            "",
            "public enum YallaColor {",
        ]
    )
    for group_name, group in colors["schemes"]["light"].items():
        for token_name in group:
            name = swift_color_name((group_name, token_name))
            lines.append(f"    public static let {name}: Color = platformColor(YallaUIColor.{name})")
    for token_name in colors["accent"]:
        name = swift_color_name(("accent", token_name))
        lines.append(f"    public static let {name}: Color = platformColor(YallaUIColor.{name})")
    lines.extend(
        [
            "",
            "    private static func platformColor(_ color: YallaNativeColor) -> Color {",
            "        #if canImport(UIKit)",
            "        return Color(uiColor: color)",
            "        #elseif canImport(AppKit)",
            "        return Color(nsColor: color)",
            "        #endif",
            "    }",
        ]
    )
    lines.append("}")
    write_text(out_dir / "ios" / "Sources" / "YallaDesignIOS" / "YallaColors.swift", "\n".join(lines) + "\n")

def generate_ios_fonts(tokens: dict, out_dir: Path) -> None:
    styles = tokens["fonts"]["styles"]
    resources = tokens["fonts"]["fontResources"]["ios"]

    def style_expr(key: str) -> str:
        style = styles[key]
        return (
            f"YallaTextStyle(fontResourceName: \"{resources[style['font']]}\", "
            f"size: {format_number(style['sizeSp'])}, "
            f"lineHeight: {format_number(style['lineHeightSp'])})"
        )

    lines = [
        "import CoreGraphics",
        "import CoreText",
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "public typealias YallaNativeFont = UIFont",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "public typealias YallaNativeFont = NSFont",
        "#endif",
        "import YallaResourcesIOS",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public struct YallaTextStyle: Sendable {",
        "    public let fontResourceName: String",
        "    public let size: CGFloat",
        "    public let lineHeight: CGFloat",
        "",
        "    public init(fontResourceName: String, size: CGFloat, lineHeight: CGFloat) {",
        "        self.fontResourceName = fontResourceName",
        "        self.size = size",
        "        self.lineHeight = lineHeight",
        "    }",
        "",
        "    public var nativeFont: YallaNativeFont {",
        "        if let url = YallaResourcesIOS.fontURL(fontResourceName),",
        "           let provider = CGDataProvider(url: url as CFURL),",
        "           let cgFont = CGFont(provider) {",
        "            let ctFont = CTFontCreateWithGraphicsFont(cgFont, size, nil, nil)",
        "            let descriptor = CTFontCopyFontDescriptor(ctFont)",
        "            #if canImport(UIKit)",
        "            return UIFont(descriptor: descriptor as UIFontDescriptor, size: size)",
        "            #elseif canImport(AppKit)",
        "            return NSFont(descriptor: descriptor as NSFontDescriptor, size: size) ?? NSFont.systemFont(ofSize: size)",
        "            #endif",
        "        }",
        "        #if canImport(UIKit)",
        "        return UIFont.systemFont(ofSize: size)",
        "        #elseif canImport(AppKit)",
        "        return NSFont.systemFont(ofSize: size)",
        "        #endif",
        "    }",
        "",
        "    #if canImport(UIKit)",
        "    public var uiFont: UIFont { nativeFont }",
        "    #elseif canImport(AppKit)",
        "    public var nsFont: NSFont { nativeFont }",
        "    #endif",
        "",
        "    public var swiftUIFont: Font {",
        "        Font.custom(fontResourceName, size: size)",
        "    }",
        "}",
        "",
        "public enum YallaFonts {",
        "    public enum Title {",
        f"        public static let xLarge = {style_expr('title.xLarge')}",
        f"        public static let large = {style_expr('title.large')}",
        f"        public static let base = {style_expr('title.base')}",
        "    }",
        "",
        "    public enum Body {",
        f"        public static let caption = {style_expr('body.caption')}",
        "",
        "        public enum Large {",
        f"            public static let regular = {style_expr('body.large.regular')}",
        f"            public static let medium = {style_expr('body.large.medium')}",
        f"            public static let bold = {style_expr('body.large.bold')}",
        "        }",
        "",
        "        public enum Base {",
        f"            public static let regular = {style_expr('body.base.regular')}",
        f"            public static let medium = {style_expr('body.base.medium')}",
        f"            public static let bold = {style_expr('body.base.bold')}",
        "        }",
        "",
        "        public enum Small {",
        f"            public static let regular = {style_expr('body.small.regular')}",
        f"            public static let medium = {style_expr('body.small.medium')}",
        f"            public static let bold = {style_expr('body.small.bold')}",
        "        }",
        "    }",
        "",
        "    public enum Custom {",
        f"        public static let carNumber = {style_expr('custom.carNumber')}",
        "    }",
        "}",
    ]
    write_text(out_dir / "ios" / "Sources" / "YallaDesignIOS" / "YallaFonts.swift", "\n".join(lines) + "\n")

def generate_ios_themed_images(tokens: dict, out_dir: Path) -> None:
    images = tokens["themedImages"]["images"]
    lines = [
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "#endif",
        "import YallaResourcesIOS",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public enum YallaThemedImage: String, CaseIterable, Sendable {",
    ]
    for image in images:
        lines.append(f"    case {swift_case_name(image['name'])} = \"{image['name']}\"")
    lines.extend(
        [
            "",
            "    public var assetName: String {",
            "        switch self {",
        ]
    )
    for image in images:
        lines.append(f"        case .{swift_case_name(image['name'])}:")
        lines.append(f"            return \"{resource_alias_name(image['name'])}\"")
    lines.extend(
        [
            "        }",
            "    }",
            "",
            "    #if canImport(UIKit)",
            "    public func uiImage(compatibleWith traitCollection: UITraitCollection? = nil) -> UIImage? {",
            "        return YallaResourcesIOS.platformImage(assetName, compatibleWith: traitCollection)",
            "    }",
            "    #elseif canImport(AppKit)",
            "    public func nsImage() -> NSImage? {",
            "        return YallaResourcesIOS.platformImage(assetName)",
            "    }",
            "    #endif",
            "",
            "    @available(iOS 13.0, macOS 10.15, *)",
            "    public var image: Image {",
            "        YallaResourcesIOS.swiftUIImage(assetName)",
            "    }",
            "}",
        ]
    )
    write_text(out_dir / "ios" / "Sources" / "YallaDesignIOS" / "YallaThemedImage.swift", "\n".join(lines) + "\n")

def generate_ios_design(tokens: dict, out_dir: Path) -> None:
    generate_ios_colors(tokens, out_dir)
    generate_ios_fonts(tokens, out_dir)
    generate_ios_themed_images(tokens, out_dir)

# endregion

def generate(out_dir: Path, tokens: dict | None = None) -> None:
    tokens = validate(tokens)
    clean_dir(out_dir)
    generate_metadata(tokens, out_dir)
    generate_cmp_design(tokens, out_dir)
    generate_android_design(tokens, out_dir)
    generate_ios_design(tokens, out_dir)
