from __future__ import annotations
import shutil
from pathlib import Path
from .io import write_text, write_json, clean_dir
from .formatters import *
from .validation import validate

def generate(out_dir: Path, tokens: dict | None = None) -> None:
    tokens = validate(tokens)
    clean_dir(out_dir)
    generate_metadata(tokens, out_dir)
    (out_dir / "cmp").mkdir(parents=True, exist_ok=True)
    (out_dir / "ios").mkdir(parents=True, exist_ok=True)
    # Re-implementing generation calls
    generate_android_design(tokens, out_dir)

def generate_metadata(tokens: dict, out_dir: Path) -> None:
    write_json(out_dir / "metadata" / "yalla-design.json", tokens)

def generate_android_colors(tokens: dict, out_dir: Path) -> None:
    for scheme in ["light", "dark"]:
        lines = [
            "package uz.yalla.design.color",
            "",
            "import androidx.compose.ui.graphics.Color",
            "",
            f"// {scheme.capitalize()} mode colors",
            "",
        ]
        colors = tokens["colors"]["schemes"][scheme]
        for group_name, group in colors.items():
            for token_name, color in group.items():
                name = android_color_name((scheme, group_name, token_name))
                lines.append(f"internal val {name} = Color({argb_literal(color)})")
        
        if scheme == "light":
             for token_name, color in tokens["colors"]["accent"].items():
                name = android_color_name(("accent", token_name))
                lines.append(f"internal val {name} = Color({argb_literal(color)})")
             for gradient_name, stops in tokens["colors"]["gradients"].items():
                 for index, stop in enumerate(stops):
                    name = android_color_name(("gradient", gradient_name, str(index)))
                    lines.append(f"internal val {name} = Color({argb_literal(stop['color'])})")

        write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "design" / "color" / f"Colors_{scheme.capitalize()}.kt", "\n".join(lines) + "\n")

def generate_android_themed_image_drawables(tokens: dict, out_dir: Path) -> None:
    for variant, folder in (("light", "drawable"), ("dark", "drawable-night")):
        for image in tokens["themedImages"]["images"]:
            lines = [
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
                "<!-- Generated by yalla-design. Do not edit manually. -->",
                "<bitmap xmlns:android=\"http://schemas.android.com/apk/res/android\"",
                f"    android:src=\"@drawable/{image[variant]}\" />",
            ]
            filename = resource_alias_name(image['name']) + ".xml"
            write_text(out_dir / "android" / "design" / "src" / "main" / "res" / folder / filename, "\n".join(lines) + "\n")

def generate_android_color_helpers(tokens: dict, out_dir: Path) -> None:
    colors = tokens["colors"]
    lines = [
        "package uz.yalla.design.color",
        "",
        "import androidx.compose.ui.graphics.Color",
        "",
        "object YallaColors {",
    ]
    for group_name, group in colors["schemes"]["light"].items():
        lines.append(f"    object {pascal_case(group_name)} {{")
        for token_name in group:
            val_name = android_color_name(("light", group_name, token_name))
            lines.append(f"        val {camel_case(token_name)}: Color get() = {val_name}")
        lines.append("    }")
        lines.append("")
    lines.append("    object Accent {")
    for token_name in tokens["colors"]["accent"]:
        val_name = android_color_name(("accent", token_name))
        lines.append(f"        val {camel_case(token_name)}: Color get() = {val_name}")
    lines.append("    }")
    lines.append("")
    lines.append("    object Gradient {")
    for gradient_name, stops in colors["gradients"].items():
        resource_names = ", ".join(android_color_name(("gradient", gradient_name, str(index))) for index, _ in enumerate(stops))
        lines.append(f"        val {camel_case(gradient_name)}: List<Color> get() = listOf({resource_names})")
    lines.append("    }")
    lines.append("}")
    write_text(out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "design" / "color" / "YallaColors.kt", "\n".join(lines) + "\n")

def generate_android_design(tokens: dict, out_dir: Path) -> None:
    generate_android_colors(tokens, out_dir)
    generate_android_themed_image_drawables(tokens, out_dir)
    generate_android_color_helpers(tokens, out_dir)
