from __future__ import annotations
import shutil
from pathlib import Path
from .io import write_text, write_json, clean_dir
from .formatters import *
from .validation import validate

def generate(out_dir: Path, tokens: dict | None = None) -> None:
    tokens = validate(tokens)
    clean_dir(out_dir)
    generate_metadata(tokens, out_dir)
    generate_cmp_design(tokens, out_dir)
    generate_android_design(tokens, out_dir)
    generate_ios_design(tokens, out_dir)

def generate_metadata(tokens: dict, out_dir: Path) -> None:
    write_json(out_dir / "metadata" / "yalla-design.json", tokens)

# region Shared Emitters

def generate_kotlin_colors(tokens: dict, out_path: Path, package: str) -> None:
    # Color.kt
    color_lines = [
        f"package {package}",
        "",
        "import androidx.compose.ui.geometry.Offset",
        "import androidx.compose.ui.graphics.Brush",
        "import androidx.compose.ui.graphics.Color",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
    ]
    for scheme in ["light", "dark"]:
        color_lines.append(f"// region {scheme.capitalize()} Theme Colors")
        color_lines.append("")
        colors = tokens["colors"]["schemes"][scheme]
        for group_name, group in colors.items():
            for token_name, color in group.items():
                symbol = kotlin_symbol((scheme, group_name, token_name))
                color_lines.append(f"internal val {symbol} = {kotlin_color_literal(color)}")
        color_lines.append("")
        color_lines.append("// endregion")
        color_lines.append("")

    color_lines.append("// region Accent Colors")
    color_lines.append("")
    for token_name, color in tokens["colors"]["accent"].items():
        symbol = kotlin_accent_symbol(token_name)
        color_lines.append(f"internal val {symbol} = {kotlin_color_literal(color)}")
    color_lines.append("")
    color_lines.append("// endregion")
    color_lines.append("")

    color_lines.append("// region Gradients")
    color_lines.append("")
    for gradient_name, stops in tokens["colors"]["gradients"].items():
        symbol = kotlin_gradient_symbol(gradient_name)
        colors_list = ", ".join(kotlin_color_literal(stop["color"]) for stop in stops)
        if gradient_name == "splash":
            color_lines.append(f"internal val {symbol} = Brush.linearGradient(")
            color_lines.append(f"    colors = listOf({colors_list}),")
            color_lines.append("    start = Offset(0f, 0f),")
            color_lines.append("    end = Offset(1000f, 1000f)")
            color_lines.append(")")
        else:
            color_lines.append(f"internal val {symbol} = Brush.linearGradient(listOf({colors_list}))")
    color_lines.append("")
    color_lines.append("// endregion")

    write_text(out_path / "Color.kt", "\n".join(color_lines) + "\n")


    # ColorScheme.kt
    scheme_lines = [
        f"package {package}",
        "",
        "import androidx.compose.runtime.Immutable",
        "import androidx.compose.runtime.staticCompositionLocalOf",
        "import androidx.compose.ui.graphics.Brush",
        "import androidx.compose.ui.graphics.Color",
        "",
        "@Immutable",
        "data class ColorScheme(",
    ]
    groups = tokens["colors"]["schemes"]["light"]
    for group_name in groups:
        scheme_lines.append(f"    val {camel_case(group_name)}: {pascal_case(group_name)},")
    scheme_lines.append("    val accent: Accent,")
    scheme_lines.append("    val gradient: Gradient")
    scheme_lines.append(") {")

    for group_name, group in groups.items():
        scheme_lines.append("    @Immutable")
        scheme_lines.append(f"    data class {pascal_case(group_name)}(")
        for token_name in group:
            scheme_lines.append(f"        val {camel_case(token_name)}: Color,")
        scheme_lines.append("    )")
        scheme_lines.append("")

    scheme_lines.append("    @Immutable")
    scheme_lines.append("    data class Accent(")
    for token_name in tokens["colors"]["accent"]:
        scheme_lines.append(f"        val {camel_case(token_name)}: Color,")
    scheme_lines.append("    )")
    scheme_lines.append("")

    scheme_lines.append("    @Immutable")
    scheme_lines.append("    data class Gradient(")
    for gradient_name in tokens["colors"]["gradients"]:
        scheme_lines.append(f"        val {camel_case(gradient_name)}: Brush,")
    scheme_lines.append("    )")
    scheme_lines.append("}")
    scheme_lines.append("")

    for scheme in ["light", "dark"]:
        scheme_lines.append(f"fun {scheme}() =")
        scheme_lines.append("    ColorScheme(")
        for group_name, group in tokens["colors"]["schemes"][scheme].items():
            scheme_lines.append(f"        {camel_case(group_name)} =")
            scheme_lines.append(f"            ColorScheme.{pascal_case(group_name)}(")
            for token_name in group:
                symbol = kotlin_symbol((scheme, group_name, token_name))
                scheme_lines.append(f"                {camel_case(token_name)} = {symbol},")
            scheme_lines.append("            ),")
        
        scheme_lines.append("        accent =")
        scheme_lines.append("            ColorScheme.Accent(")
        for token_name in tokens["colors"]["accent"]:
            symbol = kotlin_accent_symbol(token_name)
            scheme_lines.append(f"                {camel_case(token_name)} = {symbol},")
        scheme_lines.append("            ),")

        scheme_lines.append("        gradient =")
        scheme_lines.append("            ColorScheme.Gradient(")
        for gradient_name in tokens["colors"]["gradients"]:
            symbol = kotlin_gradient_symbol(gradient_name)
            scheme_lines.append(f"                {camel_case(gradient_name)} = {symbol},")
        scheme_lines.append("            )")
        scheme_lines.append("    )")
        scheme_lines.append("")

    scheme_lines.append("val LocalColorScheme = staticCompositionLocalOf { light() }")

    write_text(out_path / "ColorScheme.kt", "\n".join(scheme_lines) + "\n")

def generate_kotlin_fonts(tokens: dict, out_path: Path, package: str) -> None:
    # FontScheme.kt
    lines = [
        f"package {package}",
        "",
        "import androidx.compose.runtime.Immutable",
        "import androidx.compose.runtime.staticCompositionLocalOf",
        "import androidx.compose.ui.text.TextStyle",
        "",
        "@Immutable",
        "data class FontScheme(",
        "    val title: Title,",
        "    val body: Body,",
        "    val custom: Custom",
        ") {",
        "    @Immutable",
        "    data class Title(",
        "        val xLarge: TextStyle,",
        "        val large: TextStyle,",
        "        val base: TextStyle",
        "    )",
        "",
        "    @Immutable",
        "    data class Body(",
        "        val caption: TextStyle,",
        "        val large: Weighty,",
        "        val base: Weighty,",
        "        val small: Weighty",
        "    ) {",
        "        @Immutable",
        "        data class Weighty(",
        "            val regular: TextStyle,",
        "            val medium: TextStyle,",
        "            val bold: TextStyle",
        "        )",
        "    }",
        "",
        "    @Immutable",
        "    data class Custom(",
        "        val carNumber: TextStyle",
        "    )",
        "}",
        "",
        "val LocalFontScheme =",
        "    staticCompositionLocalOf<FontScheme> {",
        "        error(\"No FontScheme provided. Wrap your content with YallaTheme or provide a FontScheme via LocalFontScheme.\")",
        "    }",
    ]
    write_text(out_path / "FontScheme.kt", "\n".join(lines) + "\n")

def generate_kotlin_theme(tokens: dict, out_path: Path, package: str, color_package: str, font_package: str) -> None:
    lines = [
        f"package {package}",
        "",
        "import androidx.compose.foundation.isSystemInDarkTheme",
        "import androidx.compose.material.ripple.RippleAlpha",
        "import androidx.compose.material3.ExperimentalMaterial3Api",
        "import androidx.compose.material3.LocalRippleConfiguration",
        "import androidx.compose.material3.MaterialTheme",
        "import androidx.compose.material3.RippleConfiguration",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.runtime.CompositionLocalProvider",
        "import androidx.compose.runtime.staticCompositionLocalOf",
        "import androidx.compose.ui.graphics.Color",
        f"import {color_package}.ColorScheme",
        f"import {color_package}.LocalColorScheme",
        f"import {color_package}.dark",
        f"import {color_package}.light",
        f"import {font_package}.FontScheme",
        f"import {font_package}.LocalFontScheme",
        f"import {font_package}.rememberFontScheme",
        "import androidx.compose.material3.darkColorScheme as materialDarkColorScheme",
        "import androidx.compose.material3.lightColorScheme as materialLightColorScheme",
        "",
        "internal val LocalIsDark = staticCompositionLocalOf { false }",
        "",
        "@OptIn(ExperimentalMaterial3Api::class)",
        "@Composable",
        "fun YallaTheme(",
        "    isDark: Boolean = isSystemInDarkTheme(),",
        "    colorScheme: ColorScheme = if (isDark) dark() else light(),",
        "    fontScheme: FontScheme = rememberFontScheme(),",
        "    content: @Composable () -> Unit",
        ") {",
        "    val rippleConfiguration =",
        "        RippleConfiguration(",
        "            color = if (isDark) Color.White else Color.Black,",
        "            rippleAlpha =",
        "                RippleAlpha(",
        "                    pressedAlpha = 0.12f,",
        "                    focusedAlpha = 0.08f,",
        "                    draggedAlpha = 0.12f,",
        "                    hoveredAlpha = 0.08f",
        "                )",
        "        )",
        "",
        "    val materialColorScheme =",
        "        if (isDark) {",
        "            materialDarkColorScheme(",
        "                primary = colorScheme.button.active,",
        "                onPrimary = colorScheme.text.white,",
        "                secondary = colorScheme.button.secondary,",
        "                tertiary = colorScheme.button.tertiary,",
        "                background = colorScheme.background.base,",
        "                surface = colorScheme.background.secondary,",
        "                error = colorScheme.text.red,",
        "                onBackground = colorScheme.text.base,",
        "                onSurface = colorScheme.text.base",
        "            )",
        "        } else {",
        "            materialLightColorScheme(",
        "                primary = colorScheme.button.active,",
        "                onPrimary = colorScheme.text.white,",
        "                secondary = colorScheme.button.secondary,",
        "                tertiary = colorScheme.button.tertiary,",
        "                background = colorScheme.background.base,",
        "                surface = colorScheme.background.secondary,",
        "                error = colorScheme.text.red,",
        "                onBackground = colorScheme.text.base,",
        "                onSurface = colorScheme.text.base",
        "            )",
        "        }",
        "",
        "    CompositionLocalProvider(",
        "        LocalIsDark provides isDark,",
        "        LocalColorScheme provides colorScheme,",
        "        LocalFontScheme provides fontScheme,",
        "        LocalRippleConfiguration provides rippleConfiguration",
        "    ) {",
        "        MaterialTheme(",
        "            colorScheme = materialColorScheme,",
        "            content = content",
        "        )",
        "    }",
        "}",
        "",
        "object System {",
        "    val color: ColorScheme",
        "        @Composable",
        "        get() = LocalColorScheme.current",
        "",
        "    val font: FontScheme",
        "        @Composable",
        "        get() = LocalFontScheme.current",
        "}",
    ]
    write_text(out_path / "Theme.kt", "\n".join(lines) + "\n")

# endregion

# region CMP Emitters

def generate_cmp_design(tokens: dict, out_dir: Path) -> None:
    package = "uz.yalla.design"
    base_path = out_dir / "cmp" / "design" / "src" / "commonMain" / "kotlin" / "uz" / "yalla" / "design"
    generate_kotlin_colors(tokens, base_path / "color", f"{package}.color")
    generate_kotlin_fonts(tokens, base_path / "font", f"{package}.font")
    generate_kotlin_theme(tokens, base_path / "theme", f"{package}.theme", f"{package}.color", f"{package}.font")
    generate_cmp_fonts_impl(tokens, base_path / "font")
    generate_cmp_images(tokens, base_path / "image")

def generate_cmp_fonts_impl(tokens: dict, out_path: Path) -> None:
    lines = [
        "package uz.yalla.design.font",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.FontFamily",
        "import androidx.compose.ui.unit.sp",
        "import org.jetbrains.compose.resources.Font",
        "import org.jetbrains.compose.resources.FontResource",
        "import uz.yalla.resources.Res",
        "import uz.yalla.resources.nummernschild",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
    ]
    for role in ["bold", "medium", "normal"]:
        lines.append(f"expect val {role}Font: FontResource")
    lines.append("")
    lines.append("@Composable")
    lines.append("fun rememberFontScheme(): FontScheme =")
    lines.append("    FontScheme(")
    
    styles = tokens["fonts"]["styles"]
    
    lines.append("        title =")
    lines.append("            FontScheme.Title(")
    lines.append(f"                xLarge = TextStyle(fontSize = {kotlin_sp(styles['title.xLarge']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.xLarge']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('bold')}))),")
    lines.append(f"                large = TextStyle(fontSize = {kotlin_sp(styles['title.large']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.large']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('bold')}))),")
    lines.append(f"                base = TextStyle(fontSize = {kotlin_sp(styles['title.base']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.base']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('bold')})))")
    lines.append("            ),")
    
    lines.append("        body =")
    lines.append("            FontScheme.Body(")
    lines.append(f"                caption = TextStyle(fontSize = {kotlin_sp(styles['body.caption']['sizeSp'])}, lineHeight = {kotlin_sp(styles['body.caption']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('medium')}))),")
    for size in ["large", "base", "small"]:
        lines.append(f"                {size} =")
        lines.append("                    FontScheme.Body.Weighty(")
        lines.append(f"                        regular = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.regular']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.regular']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('normal')}))),")
        lines.append(f"                        medium = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.medium']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.medium']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('medium')}))),")
        lines.append(f"                        bold = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.bold']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.bold']['lineHeightSp'])}, fontFamily = FontFamily(Font({kotlin_font_ref('bold')})))")
        lines.append("                    ),")
    lines.pop() # remove last comma
    lines.append("                    )")
    lines.append("            ),")
    
    lines.append("        custom =")
    lines.append("            FontScheme.Custom(")
    lines.append(f"                carNumber = TextStyle(fontSize = {kotlin_sp(styles['custom.carNumber']['sizeSp'])}, lineHeight = {kotlin_sp(styles['custom.carNumber']['lineHeightSp'])}, fontFamily = FontFamily(Font(Res.font.nummernschild)))")
    lines.append("            )")
    lines.append("    )")
    
    write_text(out_path / "Font.kt", "\n".join(lines) + "\n")

def generate_cmp_images(tokens: dict, out_path: Path) -> None:
    # ThemedImage.kt
    lines = [
        "package uz.yalla.design.image",
        "",
        "import org.jetbrains.compose.resources.DrawableResource",
        "import uz.yalla.resources.Res",
    ]
    images = tokens["themedImages"]["images"]
    for image in images:
        lines.append(f"import uz.yalla.resources.{image['light']}")
        lines.append(f"import uz.yalla.resources.{image['dark']}")
    lines.append("")
    lines.append("// Generated by yalla-design. Do not edit manually.")
    lines.append("")
    lines.append("enum class ThemedImage(")
    lines.append("    val light: DrawableResource,")
    lines.append("    val dark: DrawableResource")
    lines.append(") {")
    for image in images:
        lines.append(f"    {image['name']}(Res.drawable.{image['light']}, Res.drawable.{image['dark']}),")
    lines.append("}")
    write_text(out_path / "ThemedImage.kt", "\n".join(lines) + "\n")

    # ThemedPainter.kt
    painter_lines = [
        "package uz.yalla.design.image",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.graphics.painter.Painter",
        "import org.jetbrains.compose.resources.painterResource",
        "import uz.yalla.design.theme.LocalIsDark",
        "",
        "@Composable",
        "fun themedPainter(image: ThemedImage): Painter {",
        "    val resource = if (LocalIsDark.current) image.dark else image.light",
        "    return painterResource(resource)",
        "}",
    ]
    write_text(out_path / "ThemedPainter.kt", "\n".join(painter_lines) + "\n")

# endregion

# region Android Emitters

def generate_android_design(tokens: dict, out_dir: Path) -> None:
    package = "uz.yalla.sdk.android.design"
    base_path = out_dir / "android" / "design" / "src" / "main" / "kotlin" / "uz" / "yalla" / "sdk" / "android" / "design"
    generate_kotlin_colors(tokens, base_path / "color", f"{package}.color")
    generate_kotlin_fonts(tokens, base_path / "font", f"{package}.font")
    generate_kotlin_theme(tokens, base_path / "theme", f"{package}.theme", f"{package}.color", f"{package}.font")
    generate_android_fonts_impl(tokens, base_path / "font", package)
    generate_android_images(tokens, base_path / "image", package)
    generate_android_themed_image_drawables(tokens, out_dir)

def generate_android_fonts_impl(tokens: dict, out_path: Path, package: str) -> None:
    lines = [
        f"package {package}.font",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.Font",
        "import androidx.compose.ui.text.font.FontFamily",
        "import androidx.compose.ui.unit.sp",
        "import uz.yalla.sdk.android.design.R",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "@Composable",
        "fun rememberFontScheme(): FontScheme {",
    ]
    font_res = tokens["fonts"]["fontResources"]["android"]
    for role, res in font_res.items():
        if role != "carNumber":
            lines.append(f"    val {role}Font = FontFamily(Font(R.font.{res}))")
    lines.append("")
    lines.append("    return FontScheme(")
    
    styles = tokens["fonts"]["styles"]
    
    lines.append("        title =")
    lines.append("            FontScheme.Title(")
    lines.append(f"                xLarge = TextStyle(fontSize = {kotlin_sp(styles['title.xLarge']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.xLarge']['lineHeightSp'])}, fontFamily = {styles['title.xLarge']['font']}Font),")
    lines.append(f"                large = TextStyle(fontSize = {kotlin_sp(styles['title.large']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.large']['lineHeightSp'])}, fontFamily = {styles['title.large']['font']}Font),")
    lines.append(f"                base = TextStyle(fontSize = {kotlin_sp(styles['title.base']['sizeSp'])}, lineHeight = {kotlin_sp(styles['title.base']['lineHeightSp'])}, fontFamily = {styles['title.base']['font']}Font)")
    lines.append("            ),")
    
    lines.append("        body =")
    lines.append("            FontScheme.Body(")
    lines.append(f"                caption = TextStyle(fontSize = {kotlin_sp(styles['body.caption']['sizeSp'])}, lineHeight = {kotlin_sp(styles['body.caption']['lineHeightSp'])}, fontFamily = {styles['body.caption']['font']}Font),")
    for size in ["large", "base", "small"]:
        lines.append(f"                {size} =")
        lines.append("                    FontScheme.Body.Weighty(")
        lines.append(f"                        regular = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.regular']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.regular']['lineHeightSp'])}, fontFamily = {styles[f'body.{size}.regular']['font']}Font),")
        lines.append(f"                        medium = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.medium']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.medium']['lineHeightSp'])}, fontFamily = {styles[f'body.{size}.medium']['font']}Font),")
        lines.append(f"                        bold = TextStyle(fontSize = {kotlin_sp(styles[f'body.{size}.bold']['sizeSp'])}, lineHeight = {kotlin_sp(styles[f'body.{size}.bold']['lineHeightSp'])}, fontFamily = {styles[f'body.{size}.bold']['font']}Font)")
        lines.append("                    ),")
    lines.pop() # remove last comma
    lines.append("                    )")
    lines.append("            ),")
    
    lines.append("        custom =")
    lines.append("            FontScheme.Custom(")
    lines.append(f"                carNumber = TextStyle(fontSize = {kotlin_sp(styles['custom.carNumber']['sizeSp'])}, lineHeight = {kotlin_sp(styles['custom.carNumber']['lineHeightSp'])}, fontFamily = FontFamily(Font(R.font.{font_res['carNumber']})))")
    lines.append("            )")
    lines.append("    )")
    lines.append("}")
    
    write_text(out_path / "Font.kt", "\n".join(lines) + "\n")

def generate_android_images(tokens: dict, out_path: Path, package: str) -> None:
    # ThemedImage.kt
    lines = [
        f"package {package}.image",
        "",
        "import uz.yalla.sdk.android.design.R",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "enum class ThemedImage(",
        "    val light: Int,",
        "    val dark: Int",
        ") {",
    ]
    images = tokens["themedImages"]["images"]
    for image in images:
        lines.append(f"    {image['name']}(R.drawable.{image['light']}, R.drawable.{image['dark']}),")
    lines.append("}")
    write_text(out_path / "ThemedImage.kt", "\n".join(lines) + "\n")

    # ThemedPainter.kt
    painter_lines = [
        f"package {package}.image",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.ui.graphics.painter.Painter",
        "import androidx.compose.ui.res.painterResource",
        f"import {package}.theme.LocalIsDark",
        "",
        "@Composable",
        "fun themedPainter(image: ThemedImage): Painter {",
        "    val resource = if (LocalIsDark.current) image.dark else image.light",
        "    return painterResource(resource)",
        "}",
    ]
    write_text(out_path / "ThemedPainter.kt", "\n".join(painter_lines) + "\n")

def generate_android_themed_image_drawables(tokens: dict, out_dir: Path) -> None:
    for variant, folder in (("light", "drawable"), ("dark", "drawable-night")):
        for image in tokens["themedImages"]["images"]:
            lines = [
                "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
                "<!-- Generated by yalla-design. Do not edit manually. -->",
                "<bitmap xmlns:android=\"http://schemas.android.com/apk/res/android\"",
                f"    android:src=\"@drawable/{image[variant]}\" />",
            ]
            filename = resource_alias_name(image['name']) + ".xml"
            write_text(out_dir / "android" / "design" / "src" / "main" / "res" / folder / filename, "\n".join(lines) + "\n")

# endregion


# region iOS Emitters

def generate_ios_design(tokens: dict, out_dir: Path) -> None:
    base_path = out_dir / "ios" / "Sources" / "YallaDesignIOS"
    generate_ios_colors(tokens, base_path)
    generate_ios_fonts(tokens, base_path)
    generate_ios_images(tokens, base_path)

def generate_ios_colors(tokens: dict, out_path: Path) -> None:
    lines = [
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "public typealias YallaNativeColor = UIColor",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "public typealias YallaNativeColor = NSColor",
        "#endif",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public enum YallaUIColor {",
    ]
    
    schemes = tokens["colors"]["schemes"]
    for group_name, group in schemes["light"].items():
        for token_name, light_hex in group.items():
            dark_hex = schemes["dark"][group_name][token_name]
            lines.append(f"    public static let {camel_case(group_name)}{pascal_case(token_name)}: YallaNativeColor = dynamic(light: {argb_literal(light_hex)}, dark: {argb_literal(dark_hex)})")
    
    for token_name, hex_val in tokens["colors"]["accent"].items():
        lines.append(f"    public static let accent{pascal_case(token_name)}: YallaNativeColor = fixed({argb_literal(hex_val)})")
    
    for gradient_name, stops in tokens["colors"]["gradients"].items():
        stops_list = ", ".join(f"fixed({argb_literal(stop['color'])})" for stop in stops)
        lines.append(f"    public static let gradient{pascal_case(gradient_name)}: [YallaNativeColor] = [{stops_list}]")
    
    lines.extend([
        "",
        "    private static func dynamic(light: UInt32, dark: UInt32) -> YallaNativeColor {",
        "        #if canImport(UIKit)",
        "        return UIColor { traitCollection in",
        "            return traitCollection.userInterfaceStyle == .dark ? color(dark) : color(light)",
        "        }",
        "        #elseif canImport(AppKit)",
        "        return NSColor(name: nil) { appearance in",
        "            let bestMatch = appearance.bestMatch(from: [.aqua, .darkAqua])",
        "            return bestMatch == .darkAqua ? color(dark) : color(light)",
        "        }",
        "        #endif",
        "    }",
        "",
        "    private static func fixed(_ argb: UInt32) -> YallaNativeColor {",
        "        return color(argb)",
        "    }",
        "",
        "    private static func color(_ argb: UInt32) -> YallaNativeColor {",
        "        #if canImport(UIKit)",
        "        return UIColor(",
        "            red: CGFloat((argb >> 16) & 0xFF) / 255.0,",
        "            green: CGFloat((argb >> 8) & 0xFF) / 255.0,",
        "            blue: CGFloat(argb & 0xFF) / 255.0,",
        "            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0",
        "        )",
        "        #elseif canImport(AppKit)",
        "        return NSColor(",
        "            red: CGFloat((argb >> 16) & 0xFF) / 255.0,",
        "            green: CGFloat((argb >> 8) & 0xFF) / 255.0,",
        "            blue: CGFloat(argb & 0xFF) / 255.0,",
        "            alpha: CGFloat((argb >> 24) & 0xFF) / 255.0",
        "        )",
        "        #endif",
        "    }",
        "}",
        "",
        "public enum YallaColor {",
    ])
    
    for group_name, group in schemes["light"].items():
        for token_name in group:
            symbol = f"{camel_case(group_name)}{pascal_case(token_name)}"
            lines.append(f"    public static let {symbol}: Color = platformColor(YallaUIColor.{symbol})")
            
    for token_name in tokens["colors"]["accent"]:
        symbol = f"accent{pascal_case(token_name)}"
        lines.append(f"    public static let {symbol}: Color = platformColor(YallaUIColor.{symbol})")

    lines.extend([
        "",
        "    private static func platformColor(_ color: YallaNativeColor) -> Color {",
        "        #if canImport(UIKit)",
        "        return Color(uiColor: color)",
        "        #elseif canImport(AppKit)",
        "        return Color(nsColor: color)",
        "        #endif",
        "    }",
        "}",
    ])
    write_text(out_path / "YallaColors.swift", "\n".join(lines) + "\n")

def generate_ios_fonts(tokens: dict, out_path: Path) -> None:
    lines = [
        "import CoreGraphics",
        "import CoreText",
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "public typealias YallaNativeFont = UIFont",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "public typealias YallaNativeFont = NSFont",
        "#endif",
        "import YallaResourcesIOS",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public struct YallaTextStyle: Sendable {",
        "    public let fontResourceName: String",
        "    public let size: CGFloat",
        "    public let lineHeight: CGFloat",
        "",
        "    public init(fontResourceName: String, size: CGFloat, lineHeight: CGFloat) {",
        "        self.fontResourceName = fontResourceName",
        "        self.size = size",
        "        self.lineHeight = lineHeight",
        "    }",
        "",
        "    public var nativeFont: YallaNativeFont {",
        "        if let url = YallaResourcesIOS.fontURL(fontResourceName),",
        "           let provider = CGDataProvider(url: url as CFURL),",
        "           let cgFont = CGFont(provider) {",
        "            let ctFont = CTFontCreateWithGraphicsFont(cgFont, size, nil, nil)",
        "            let descriptor = CTFontCopyFontDescriptor(ctFont)",
        "            #if canImport(UIKit)",
        "            return UIFont(descriptor: descriptor as UIFontDescriptor, size: size)",
        "            #elseif canImport(AppKit)",
        "            return NSFont(descriptor: descriptor as NSFontDescriptor, size: size) ?? NSFont.systemFont(ofSize: size)",
        "            #endif",
        "        }",
        "        #if canImport(UIKit)",
        "        return UIFont.systemFont(ofSize: size)",
        "        #elseif canImport(AppKit)",
        "        return NSFont.systemFont(ofSize: size)",
        "        #endif",
        "    }",
        "",
        "    #if canImport(UIKit)",
        "    public var uiFont: UIFont { nativeFont }",
        "    #elseif canImport(AppKit)",
        "    public var nsFont: NSFont { nativeFont }",
        "    #endif",
        "",
        "    public var swiftUIFont: Font {",
        "        Font.custom(fontResourceName, size: size)",
        "    }",
        "}",
        "",
        "public enum YallaFonts {",
    ]
    
    styles = tokens["fonts"]["styles"]
    
    lines.append("    public enum Title {")
    lines.append(f"        public static let xLarge = YallaTextStyle(fontResourceName: \"{styles['title.xLarge']['font']}Font\", size: {styles['title.xLarge']['sizeSp']}, lineHeight: {styles['title.xLarge']['lineHeightSp']})")
    lines.append(f"        public static let large = YallaTextStyle(fontResourceName: \"{styles['title.large']['font']}Font\", size: {styles['title.large']['sizeSp']}, lineHeight: {styles['title.large']['lineHeightSp']})")
    lines.append(f"        public static let base = YallaTextStyle(fontResourceName: \"{styles['title.base']['font']}Font\", size: {styles['title.base']['sizeSp']}, lineHeight: {styles['title.base']['lineHeightSp']})")
    lines.append("    }")
    lines.append("")
    
    lines.append("    public enum Body {")
    lines.append(f"        public static let caption = YallaTextStyle(fontResourceName: \"{styles['body.caption']['font']}Font\", size: {styles['body.caption']['sizeSp']}, lineHeight: {styles['body.caption']['lineHeightSp']})")
    lines.append("")
    for size in ["Large", "Base", "Small"]:
        lines.append(f"        public enum {size} {{")
        lines.append(f"            public static let regular = YallaTextStyle(fontResourceName: \"{styles[f'body.{size.lower()}.regular']['font']}Font\", size: {styles[f'body.{size.lower()}.regular']['sizeSp']}, lineHeight: {styles[f'body.{size.lower()}.regular']['lineHeightSp']})")
        lines.append(f"            public static let medium = YallaTextStyle(fontResourceName: \"{styles[f'body.{size.lower()}.medium']['font']}Font\", size: {styles[f'body.{size.lower()}.medium']['sizeSp']}, lineHeight: {styles[f'body.{size.lower()}.medium']['lineHeightSp']})")
        lines.append(f"            public static let bold = YallaTextStyle(fontResourceName: \"{styles[f'body.{size.lower()}.bold']['font']}Font\", size: {styles[f'body.{size.lower()}.bold']['sizeSp']}, lineHeight: {styles[f'body.{size.lower()}.bold']['lineHeightSp']})")
        lines.append("        }")
    lines.append("    }")
    lines.append("")
    
    lines.append("    public enum Custom {")
    lines.append(f"        public static let carNumber = YallaTextStyle(fontResourceName: \"nummernschild\", size: {styles['custom.carNumber']['sizeSp']}, lineHeight: {styles['custom.carNumber']['lineHeightSp']})")
    lines.append("    }")
    lines.append("}")

    # Fix font names in styles
    font_res = tokens["fonts"]["fontResources"]["ios"]
    content = "\n".join(lines)
    for role, res in font_res.items():
        if role != "carNumber":
            content = content.replace(f'\"{role}Font\"', f'\"{res}\"')
    
    write_text(out_path / "YallaFonts.swift", content + "\n")

def generate_ios_images(tokens: dict, out_path: Path) -> None:
    lines = [
        "import SwiftUI",
        "#if canImport(UIKit)",
        "import UIKit",
        "#elseif canImport(AppKit)",
        "import AppKit",
        "#endif",
        "import YallaResourcesIOS",
        "",
        "// Generated by yalla-design. Do not edit manually.",
        "",
        "public enum YallaThemedImage: String, CaseIterable, Sendable {",
    ]
    
    images = tokens["themedImages"]["images"]
    for image in images:
        lines.append(f'    case {camel_case(image["name"])} = "{image["name"]}"')
    
    lines.extend([
        "",
        "    public var assetName: String {",
        "        switch self {",
    ])
    
    for image in images:
        lines.append(f'        case .{camel_case(image["name"])}: return "img_{lower_snake(image["name"])}"')
        
    lines.extend([
        "        }",
        "    }",

        "",
        "    #if canImport(UIKit)",
        "    public func uiImage(compatibleWith traitCollection: UITraitCollection? = nil) -> UIImage? {",
        "        return YallaResourcesIOS.platformImage(assetName, compatibleWith: traitCollection)",
        "    }",
        "    #elseif canImport(AppKit)",
        "    public func nsImage() -> NSImage? {",
        "        return YallaResourcesIOS.platformImage(assetName)",
        "    }",
        "    #endif",
        "",
        "    @available(iOS 13.0, macOS 10.15, *)",
        "    public var image: Image {",
        "        YallaResourcesIOS.swiftUIImage(assetName)",
        "    }",
        "}",
    ])
    write_text(out_path / "YallaThemedImage.swift", "\n".join(lines) + "\n")

# endregion
